### ISSUE TITLE
Raster: Make use of new GDAL bindings for gdalwarp

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/PythonRaster#3]
In the raster tutorial, `gdalwarp` is run on the command line using the `!` operator in Jupyter. Instead, the new GDAL bindings should be used. Example by Sytze:
```python
ndvi_ll = gdal.Warp("data/ndvi_ll.tif", outDataSet, options=gdal.WarpOptions(dstSRS="EPSG:4326"))
```

**Comment by cornehappy** [comment]
good one, now outdated as this line isn't there anymore :)
